services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.114.0
    volumes:
      - ./docker_files/otel-collector-config.yaml:/etc/otelcol/config.yaml
    command: ["--config", "/etc/otelcol/config.yaml"]
    ports:
      - "4317:4317"
      - "8888:8889"
    networks:
      - opal-network

  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ./docker_files/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - opal-network
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:9.5.3
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - opal-network

  opal_server:
    image: permitio/opal-server:0.7.16
    environment:
      - OPAL_POLICY_REPO_URL=https://github.com/permitio/opal-example-policy-repo
      - OPAL_POLICY_REPO_POLLING_INTERVAL=30
      - OPAL_DATA_CONFIG_SOURCES={"config":{"entries":[{"url":"http://opal_server:7002/policy-data","topics":["policy_data"],"dst_path":"/static"}]}}
      - OPAL_LOG_FORMAT_INCLUDE_PID=true
      - OPAL_ENABLE_OPENTELEMETRY_TRACING=true
      - OPAL_ENABLE_OPENTELEMETRY_METRICS=true
      - OPAL_OPENTELEMETRY_OTLP_ENDPOINT=otel-collector:4317
    ports:
      - "7002:7002"
    depends_on:
      - otel-collector
    networks:
      - opal-network

  opal_client:
    image: permitio/opal-client:0.7.16
    environment:
      - OPAL_SERVER_URL=http://opal_server:7002
      - OPAL_LOG_FORMAT_INCLUDE_PID=true
      - OPAL_INLINE_OPA_LOG_FORMAT=http
    ports:
      - "7766:7000"
      - "8181:8181"
    depends_on:
      - opal_server
      - otel-collector
    command: sh -c "exec ./wait-for.sh opal_server:7002 --timeout=20 -- ./start.sh"
    networks:
      - opal-network

networks:
  opal-network:
    driver: bridge
volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
